"""
this command should be run after running `promus setup` to make sure
that promus can send e-mails using the host e-mail you specified
during the setup process.

"""

import textwrap
import promus
from promus.command import disp
from promus.core import git


def add_parser(subp, raw):
    """Add a parser to the main subparser. """
    subp.add_parser('verify', help='verify promus can send emails',
                    formatter_class=raw,
                    description=textwrap.dedent(__doc__))


def run(_):
    """Run command. """
    disp('sending email ... ')
    send_to = [git.config('user.email')]
    subject = 'Promus Server Test'
    text = 'This message was generated by promus to make sure promus is ' \
           'able of sending emails.'
    promus.send_mail(send_to, subject, text, text)
    disp('done\n')
